# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from p2p_a2a.proto import a2a_pb2 as a2a__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in a2a_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class A2ANodeStub(object):
    """─── gRPC Service ────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentity = channel.unary_unary(
                '/a2a.v1.A2ANode/GetIdentity',
                request_serializer=a2a__pb2.Empty.SerializeToString,
                response_deserializer=a2a__pb2.AgentIdentity.FromString,
                _registered_method=True)
        self.PublishAgentCard = channel.unary_unary(
                '/a2a.v1.A2ANode/PublishAgentCard',
                request_serializer=a2a__pb2.AgentCard.SerializeToString,
                response_deserializer=a2a__pb2.PublishResult.FromString,
                _registered_method=True)
        self.GetAgentCard = channel.unary_unary(
                '/a2a.v1.A2ANode/GetAgentCard',
                request_serializer=a2a__pb2.AgentIdentityRequest.SerializeToString,
                response_deserializer=a2a__pb2.AgentCard.FromString,
                _registered_method=True)
        self.FindAgents = channel.unary_stream(
                '/a2a.v1.A2ANode/FindAgents',
                request_serializer=a2a__pb2.CapabilityQuery.SerializeToString,
                response_deserializer=a2a__pb2.AgentCard.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/a2a.v1.A2ANode/SendMessage',
                request_serializer=a2a__pb2.Message.SerializeToString,
                response_deserializer=a2a__pb2.SendResult.FromString,
                _registered_method=True)
        self.SubscribeInbox = channel.unary_stream(
                '/a2a.v1.A2ANode/SubscribeInbox',
                request_serializer=a2a__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=a2a__pb2.Message.FromString,
                _registered_method=True)
        self.GetInbox = channel.unary_stream(
                '/a2a.v1.A2ANode/GetInbox',
                request_serializer=a2a__pb2.InboxQuery.SerializeToString,
                response_deserializer=a2a__pb2.Message.FromString,
                _registered_method=True)
        self.GetOutbox = channel.unary_stream(
                '/a2a.v1.A2ANode/GetOutbox',
                request_serializer=a2a__pb2.OutboxQuery.SerializeToString,
                response_deserializer=a2a__pb2.Message.FromString,
                _registered_method=True)
        self.AckMessage = channel.unary_unary(
                '/a2a.v1.A2ANode/AckMessage',
                request_serializer=a2a__pb2.AckRequest.SerializeToString,
                response_deserializer=a2a__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateTask = channel.unary_unary(
                '/a2a.v1.A2ANode/CreateTask',
                request_serializer=a2a__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=a2a__pb2.Task.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/a2a.v1.A2ANode/GetTask',
                request_serializer=a2a__pb2.TaskID.SerializeToString,
                response_deserializer=a2a__pb2.Task.FromString,
                _registered_method=True)
        self.UpdateTask = channel.unary_unary(
                '/a2a.v1.A2ANode/UpdateTask',
                request_serializer=a2a__pb2.TaskStatusUpdate.SerializeToString,
                response_deserializer=a2a__pb2.Task.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/a2a.v1.A2ANode/CancelTask',
                request_serializer=a2a__pb2.TaskID.SerializeToString,
                response_deserializer=a2a__pb2.Task.FromString,
                _registered_method=True)
        self.PublishTaskEvent = channel.unary_unary(
                '/a2a.v1.A2ANode/PublishTaskEvent',
                request_serializer=a2a__pb2.TaskEvent.SerializeToString,
                response_deserializer=a2a__pb2.Empty.FromString,
                _registered_method=True)
        self.SubscribeTaskEvents = channel.unary_stream(
                '/a2a.v1.A2ANode/SubscribeTaskEvents',
                request_serializer=a2a__pb2.TaskID.SerializeToString,
                response_deserializer=a2a__pb2.TaskEvent.FromString,
                _registered_method=True)


class A2ANodeServicer(object):
    """─── gRPC Service ────────────────────────────────────────────────────────────

    """

    def GetIdentity(self, request, context):
        """Identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishAgentCard(self, request, context):
        """Registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Messaging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeInbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOutbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTask(self, request, context):
        """Tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishTaskEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTaskEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2ANodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentity,
                    request_deserializer=a2a__pb2.Empty.FromString,
                    response_serializer=a2a__pb2.AgentIdentity.SerializeToString,
            ),
            'PublishAgentCard': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishAgentCard,
                    request_deserializer=a2a__pb2.AgentCard.FromString,
                    response_serializer=a2a__pb2.PublishResult.SerializeToString,
            ),
            'GetAgentCard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentCard,
                    request_deserializer=a2a__pb2.AgentIdentityRequest.FromString,
                    response_serializer=a2a__pb2.AgentCard.SerializeToString,
            ),
            'FindAgents': grpc.unary_stream_rpc_method_handler(
                    servicer.FindAgents,
                    request_deserializer=a2a__pb2.CapabilityQuery.FromString,
                    response_serializer=a2a__pb2.AgentCard.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=a2a__pb2.Message.FromString,
                    response_serializer=a2a__pb2.SendResult.SerializeToString,
            ),
            'SubscribeInbox': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeInbox,
                    request_deserializer=a2a__pb2.SubscribeRequest.FromString,
                    response_serializer=a2a__pb2.Message.SerializeToString,
            ),
            'GetInbox': grpc.unary_stream_rpc_method_handler(
                    servicer.GetInbox,
                    request_deserializer=a2a__pb2.InboxQuery.FromString,
                    response_serializer=a2a__pb2.Message.SerializeToString,
            ),
            'GetOutbox': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOutbox,
                    request_deserializer=a2a__pb2.OutboxQuery.FromString,
                    response_serializer=a2a__pb2.Message.SerializeToString,
            ),
            'AckMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AckMessage,
                    request_deserializer=a2a__pb2.AckRequest.FromString,
                    response_serializer=a2a__pb2.Empty.SerializeToString,
            ),
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=a2a__pb2.CreateTaskRequest.FromString,
                    response_serializer=a2a__pb2.Task.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=a2a__pb2.TaskID.FromString,
                    response_serializer=a2a__pb2.Task.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=a2a__pb2.TaskStatusUpdate.FromString,
                    response_serializer=a2a__pb2.Task.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=a2a__pb2.TaskID.FromString,
                    response_serializer=a2a__pb2.Task.SerializeToString,
            ),
            'PublishTaskEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishTaskEvent,
                    request_deserializer=a2a__pb2.TaskEvent.FromString,
                    response_serializer=a2a__pb2.Empty.SerializeToString,
            ),
            'SubscribeTaskEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTaskEvents,
                    request_deserializer=a2a__pb2.TaskID.FromString,
                    response_serializer=a2a__pb2.TaskEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a.v1.A2ANode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a.v1.A2ANode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A2ANode(object):
    """─── gRPC Service ────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/GetIdentity',
            a2a__pb2.Empty.SerializeToString,
            a2a__pb2.AgentIdentity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishAgentCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/PublishAgentCard',
            a2a__pb2.AgentCard.SerializeToString,
            a2a__pb2.PublishResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/GetAgentCard',
            a2a__pb2.AgentIdentityRequest.SerializeToString,
            a2a__pb2.AgentCard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/FindAgents',
            a2a__pb2.CapabilityQuery.SerializeToString,
            a2a__pb2.AgentCard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/SendMessage',
            a2a__pb2.Message.SerializeToString,
            a2a__pb2.SendResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeInbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/SubscribeInbox',
            a2a__pb2.SubscribeRequest.SerializeToString,
            a2a__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/GetInbox',
            a2a__pb2.InboxQuery.SerializeToString,
            a2a__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOutbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/GetOutbox',
            a2a__pb2.OutboxQuery.SerializeToString,
            a2a__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/AckMessage',
            a2a__pb2.AckRequest.SerializeToString,
            a2a__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/CreateTask',
            a2a__pb2.CreateTaskRequest.SerializeToString,
            a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/GetTask',
            a2a__pb2.TaskID.SerializeToString,
            a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/UpdateTask',
            a2a__pb2.TaskStatusUpdate.SerializeToString,
            a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/CancelTask',
            a2a__pb2.TaskID.SerializeToString,
            a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishTaskEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/PublishTaskEvent',
            a2a__pb2.TaskEvent.SerializeToString,
            a2a__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/SubscribeTaskEvents',
            a2a__pb2.TaskID.SerializeToString,
            a2a__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
