# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from moltmesh.proto import a2a_pb2 as a2a__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in a2a_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class A2ANodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentity = channel.unary_unary(
                '/a2a.v1.A2ANode/GetIdentity',
                request_serializer=a2a__pb2.Empty.SerializeToString,
                response_deserializer=a2a__pb2.AgentIdentity.FromString,
                _registered_method=True)
        self.PublishAgentCard = channel.unary_unary(
                '/a2a.v1.A2ANode/PublishAgentCard',
                request_serializer=a2a__pb2.AgentCard.SerializeToString,
                response_deserializer=a2a__pb2.PublishResult.FromString,
                _registered_method=True)
        self.GetAgentCard = channel.unary_unary(
                '/a2a.v1.A2ANode/GetAgentCard',
                request_serializer=a2a__pb2.AgentIdentityRequest.SerializeToString,
                response_deserializer=a2a__pb2.AgentCard.FromString,
                _registered_method=True)
        self.FindAgents = channel.unary_stream(
                '/a2a.v1.A2ANode/FindAgents',
                request_serializer=a2a__pb2.CapabilityQuery.SerializeToString,
                response_deserializer=a2a__pb2.AgentCard.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/a2a.v1.A2ANode/SendMessage',
                request_serializer=a2a__pb2.Message.SerializeToString,
                response_deserializer=a2a__pb2.SendResult.FromString,
                _registered_method=True)
        self.SubscribeInbox = channel.unary_stream(
                '/a2a.v1.A2ANode/SubscribeInbox',
                request_serializer=a2a__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=a2a__pb2.Message.FromString,
                _registered_method=True)
        self.GetInbox = channel.unary_stream(
                '/a2a.v1.A2ANode/GetInbox',
                request_serializer=a2a__pb2.InboxQuery.SerializeToString,
                response_deserializer=a2a__pb2.Message.FromString,
                _registered_method=True)
        self.GetOutbox = channel.unary_stream(
                '/a2a.v1.A2ANode/GetOutbox',
                request_serializer=a2a__pb2.OutboxQuery.SerializeToString,
                response_deserializer=a2a__pb2.Message.FromString,
                _registered_method=True)
        self.AckMessage = channel.unary_unary(
                '/a2a.v1.A2ANode/AckMessage',
                request_serializer=a2a__pb2.AckRequest.SerializeToString,
                response_deserializer=a2a__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateTask = channel.unary_unary(
                '/a2a.v1.A2ANode/CreateTask',
                request_serializer=a2a__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=a2a__pb2.Task.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/a2a.v1.A2ANode/GetTask',
                request_serializer=a2a__pb2.TaskID.SerializeToString,
                response_deserializer=a2a__pb2.Task.FromString,
                _registered_method=True)
        self.UpdateTask = channel.unary_unary(
                '/a2a.v1.A2ANode/UpdateTask',
                request_serializer=a2a__pb2.TaskStatusUpdate.SerializeToString,
                response_deserializer=a2a__pb2.Task.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/a2a.v1.A2ANode/CancelTask',
                request_serializer=a2a__pb2.TaskID.SerializeToString,
                response_deserializer=a2a__pb2.Task.FromString,
                _registered_method=True)
        self.PublishTaskEvent = channel.unary_unary(
                '/a2a.v1.A2ANode/PublishTaskEvent',
                request_serializer=a2a__pb2.TaskEvent.SerializeToString,
                response_deserializer=a2a__pb2.Empty.FromString,
                _registered_method=True)
        self.SubscribeTaskEvents = channel.unary_stream(
                '/a2a.v1.A2ANode/SubscribeTaskEvents',
                request_serializer=a2a__pb2.TaskID.SerializeToString,
                response_deserializer=a2a__pb2.TaskEvent.FromString,
                _registered_method=True)
        self.SendFile = channel.unary_unary(
                '/a2a.v1.A2ANode/SendFile',
                request_serializer=a2a__pb2.SendFileRequest.SerializeToString,
                response_deserializer=a2a__pb2.Artifact.FromString,
                _registered_method=True)
        self.FetchFile = channel.unary_stream(
                '/a2a.v1.A2ANode/FetchFile',
                request_serializer=a2a__pb2.FetchFileRequest.SerializeToString,
                response_deserializer=a2a__pb2.FileChunk.FromString,
                _registered_method=True)
        self.CreateThread = channel.unary_unary(
                '/a2a.v1.A2ANode/CreateThread',
                request_serializer=a2a__pb2.CreateThreadRequest.SerializeToString,
                response_deserializer=a2a__pb2.Thread.FromString,
                _registered_method=True)
        self.GetThread = channel.unary_unary(
                '/a2a.v1.A2ANode/GetThread',
                request_serializer=a2a__pb2.ThreadID.SerializeToString,
                response_deserializer=a2a__pb2.Thread.FromString,
                _registered_method=True)
        self.AppendEntry = channel.unary_unary(
                '/a2a.v1.A2ANode/AppendEntry',
                request_serializer=a2a__pb2.AppendEntryRequest.SerializeToString,
                response_deserializer=a2a__pb2.AppendEntryResult.FromString,
                _registered_method=True)
        self.GetThreadEntries = channel.unary_stream(
                '/a2a.v1.A2ANode/GetThreadEntries',
                request_serializer=a2a__pb2.GetThreadEntriesRequest.SerializeToString,
                response_deserializer=a2a__pb2.ThreadEntryWithPos.FromString,
                _registered_method=True)
        self.SubscribeThread = channel.unary_stream(
                '/a2a.v1.A2ANode/SubscribeThread',
                request_serializer=a2a__pb2.SubscribeThreadRequest.SerializeToString,
                response_deserializer=a2a__pb2.ThreadEntryWithPos.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/a2a.v1.A2ANode/Ping',
                request_serializer=a2a__pb2.PingRequest.SerializeToString,
                response_deserializer=a2a__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/a2a.v1.A2ANode/Health',
                request_serializer=a2a__pb2.Empty.SerializeToString,
                response_deserializer=a2a__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListPeers = channel.unary_unary(
                '/a2a.v1.A2ANode/ListPeers',
                request_serializer=a2a__pb2.Empty.SerializeToString,
                response_deserializer=a2a__pb2.PeersResponse.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/a2a.v1.A2ANode/Publish',
                request_serializer=a2a__pb2.PublishRequest.SerializeToString,
                response_deserializer=a2a__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.SubscribeTopic = channel.unary_stream(
                '/a2a.v1.A2ANode/SubscribeTopic',
                request_serializer=a2a__pb2.SubscribeTopicRequest.SerializeToString,
                response_deserializer=a2a__pb2.TopicMessage.FromString,
                _registered_method=True)
        self.SetWebhook = channel.unary_unary(
                '/a2a.v1.A2ANode/SetWebhook',
                request_serializer=a2a__pb2.SetWebhookRequest.SerializeToString,
                response_deserializer=a2a__pb2.WebhookResponse.FromString,
                _registered_method=True)
        self.ClearWebhook = channel.unary_unary(
                '/a2a.v1.A2ANode/ClearWebhook',
                request_serializer=a2a__pb2.Empty.SerializeToString,
                response_deserializer=a2a__pb2.Empty.FromString,
                _registered_method=True)
        self.GetWebhook = channel.unary_unary(
                '/a2a.v1.A2ANode/GetWebhook',
                request_serializer=a2a__pb2.Empty.SerializeToString,
                response_deserializer=a2a__pb2.WebhookResponse.FromString,
                _registered_method=True)
        self.CreateNetwork = channel.unary_unary(
                '/a2a.v1.A2ANode/CreateNetwork',
                request_serializer=a2a__pb2.CreateNetworkRequest.SerializeToString,
                response_deserializer=a2a__pb2.NetworkInfo.FromString,
                _registered_method=True)
        self.JoinNetwork = channel.unary_unary(
                '/a2a.v1.A2ANode/JoinNetwork',
                request_serializer=a2a__pb2.JoinNetworkRequest.SerializeToString,
                response_deserializer=a2a__pb2.NetworkInfo.FromString,
                _registered_method=True)
        self.LeaveNetwork = channel.unary_unary(
                '/a2a.v1.A2ANode/LeaveNetwork',
                request_serializer=a2a__pb2.NetworkIDRequest.SerializeToString,
                response_deserializer=a2a__pb2.Empty.FromString,
                _registered_method=True)
        self.ListNetworks = channel.unary_unary(
                '/a2a.v1.A2ANode/ListNetworks',
                request_serializer=a2a__pb2.Empty.SerializeToString,
                response_deserializer=a2a__pb2.ListNetworksResponse.FromString,
                _registered_method=True)
        self.NetworkMembers = channel.unary_unary(
                '/a2a.v1.A2ANode/NetworkMembers',
                request_serializer=a2a__pb2.NetworkIDRequest.SerializeToString,
                response_deserializer=a2a__pb2.NetworkMembersResponse.FromString,
                _registered_method=True)
        self.BroadcastNetwork = channel.unary_unary(
                '/a2a.v1.A2ANode/BroadcastNetwork',
                request_serializer=a2a__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=a2a__pb2.Empty.FromString,
                _registered_method=True)
        self.SubscribeNetwork = channel.unary_stream(
                '/a2a.v1.A2ANode/SubscribeNetwork',
                request_serializer=a2a__pb2.NetworkIDRequest.SerializeToString,
                response_deserializer=a2a__pb2.BroadcastMessage.FromString,
                _registered_method=True)
        self.ClaimName = channel.unary_unary(
                '/a2a.v1.A2ANode/ClaimName',
                request_serializer=a2a__pb2.ClaimNameRequest.SerializeToString,
                response_deserializer=a2a__pb2.NameClaimResponse.FromString,
                _registered_method=True)
        self.ResolveName = channel.unary_unary(
                '/a2a.v1.A2ANode/ResolveName',
                request_serializer=a2a__pb2.ResolveNameRequest.SerializeToString,
                response_deserializer=a2a__pb2.NameClaimResponse.FromString,
                _registered_method=True)


class A2ANodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIdentity(self, request, context):
        """Identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishAgentCard(self, request, context):
        """Registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Messaging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeInbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOutbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTask(self, request, context):
        """Tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishTaskEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTaskEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFile(self, request, context):
        """Files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateThread(self, request, context):
        """Threads (Tendermint BFT)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThreadEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Diagnostics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """PubSub
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTopic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWebhook(self, request, context):
        """Webhooks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearWebhook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWebhook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNetwork(self, request, context):
        """Networks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNetworks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NetworkMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimName(self, request, context):
        """Names
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2ANodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentity,
                    request_deserializer=a2a__pb2.Empty.FromString,
                    response_serializer=a2a__pb2.AgentIdentity.SerializeToString,
            ),
            'PublishAgentCard': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishAgentCard,
                    request_deserializer=a2a__pb2.AgentCard.FromString,
                    response_serializer=a2a__pb2.PublishResult.SerializeToString,
            ),
            'GetAgentCard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentCard,
                    request_deserializer=a2a__pb2.AgentIdentityRequest.FromString,
                    response_serializer=a2a__pb2.AgentCard.SerializeToString,
            ),
            'FindAgents': grpc.unary_stream_rpc_method_handler(
                    servicer.FindAgents,
                    request_deserializer=a2a__pb2.CapabilityQuery.FromString,
                    response_serializer=a2a__pb2.AgentCard.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=a2a__pb2.Message.FromString,
                    response_serializer=a2a__pb2.SendResult.SerializeToString,
            ),
            'SubscribeInbox': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeInbox,
                    request_deserializer=a2a__pb2.SubscribeRequest.FromString,
                    response_serializer=a2a__pb2.Message.SerializeToString,
            ),
            'GetInbox': grpc.unary_stream_rpc_method_handler(
                    servicer.GetInbox,
                    request_deserializer=a2a__pb2.InboxQuery.FromString,
                    response_serializer=a2a__pb2.Message.SerializeToString,
            ),
            'GetOutbox': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOutbox,
                    request_deserializer=a2a__pb2.OutboxQuery.FromString,
                    response_serializer=a2a__pb2.Message.SerializeToString,
            ),
            'AckMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AckMessage,
                    request_deserializer=a2a__pb2.AckRequest.FromString,
                    response_serializer=a2a__pb2.Empty.SerializeToString,
            ),
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=a2a__pb2.CreateTaskRequest.FromString,
                    response_serializer=a2a__pb2.Task.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=a2a__pb2.TaskID.FromString,
                    response_serializer=a2a__pb2.Task.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=a2a__pb2.TaskStatusUpdate.FromString,
                    response_serializer=a2a__pb2.Task.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=a2a__pb2.TaskID.FromString,
                    response_serializer=a2a__pb2.Task.SerializeToString,
            ),
            'PublishTaskEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishTaskEvent,
                    request_deserializer=a2a__pb2.TaskEvent.FromString,
                    response_serializer=a2a__pb2.Empty.SerializeToString,
            ),
            'SubscribeTaskEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTaskEvents,
                    request_deserializer=a2a__pb2.TaskID.FromString,
                    response_serializer=a2a__pb2.TaskEvent.SerializeToString,
            ),
            'SendFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFile,
                    request_deserializer=a2a__pb2.SendFileRequest.FromString,
                    response_serializer=a2a__pb2.Artifact.SerializeToString,
            ),
            'FetchFile': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchFile,
                    request_deserializer=a2a__pb2.FetchFileRequest.FromString,
                    response_serializer=a2a__pb2.FileChunk.SerializeToString,
            ),
            'CreateThread': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateThread,
                    request_deserializer=a2a__pb2.CreateThreadRequest.FromString,
                    response_serializer=a2a__pb2.Thread.SerializeToString,
            ),
            'GetThread': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThread,
                    request_deserializer=a2a__pb2.ThreadID.FromString,
                    response_serializer=a2a__pb2.Thread.SerializeToString,
            ),
            'AppendEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntry,
                    request_deserializer=a2a__pb2.AppendEntryRequest.FromString,
                    response_serializer=a2a__pb2.AppendEntryResult.SerializeToString,
            ),
            'GetThreadEntries': grpc.unary_stream_rpc_method_handler(
                    servicer.GetThreadEntries,
                    request_deserializer=a2a__pb2.GetThreadEntriesRequest.FromString,
                    response_serializer=a2a__pb2.ThreadEntryWithPos.SerializeToString,
            ),
            'SubscribeThread': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeThread,
                    request_deserializer=a2a__pb2.SubscribeThreadRequest.FromString,
                    response_serializer=a2a__pb2.ThreadEntryWithPos.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=a2a__pb2.PingRequest.FromString,
                    response_serializer=a2a__pb2.PingResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=a2a__pb2.Empty.FromString,
                    response_serializer=a2a__pb2.HealthResponse.SerializeToString,
            ),
            'ListPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeers,
                    request_deserializer=a2a__pb2.Empty.FromString,
                    response_serializer=a2a__pb2.PeersResponse.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=a2a__pb2.PublishRequest.FromString,
                    response_serializer=a2a__pb2.PublishResponse.SerializeToString,
            ),
            'SubscribeTopic': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTopic,
                    request_deserializer=a2a__pb2.SubscribeTopicRequest.FromString,
                    response_serializer=a2a__pb2.TopicMessage.SerializeToString,
            ),
            'SetWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWebhook,
                    request_deserializer=a2a__pb2.SetWebhookRequest.FromString,
                    response_serializer=a2a__pb2.WebhookResponse.SerializeToString,
            ),
            'ClearWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearWebhook,
                    request_deserializer=a2a__pb2.Empty.FromString,
                    response_serializer=a2a__pb2.Empty.SerializeToString,
            ),
            'GetWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWebhook,
                    request_deserializer=a2a__pb2.Empty.FromString,
                    response_serializer=a2a__pb2.WebhookResponse.SerializeToString,
            ),
            'CreateNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNetwork,
                    request_deserializer=a2a__pb2.CreateNetworkRequest.FromString,
                    response_serializer=a2a__pb2.NetworkInfo.SerializeToString,
            ),
            'JoinNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinNetwork,
                    request_deserializer=a2a__pb2.JoinNetworkRequest.FromString,
                    response_serializer=a2a__pb2.NetworkInfo.SerializeToString,
            ),
            'LeaveNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveNetwork,
                    request_deserializer=a2a__pb2.NetworkIDRequest.FromString,
                    response_serializer=a2a__pb2.Empty.SerializeToString,
            ),
            'ListNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNetworks,
                    request_deserializer=a2a__pb2.Empty.FromString,
                    response_serializer=a2a__pb2.ListNetworksResponse.SerializeToString,
            ),
            'NetworkMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.NetworkMembers,
                    request_deserializer=a2a__pb2.NetworkIDRequest.FromString,
                    response_serializer=a2a__pb2.NetworkMembersResponse.SerializeToString,
            ),
            'BroadcastNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastNetwork,
                    request_deserializer=a2a__pb2.BroadcastRequest.FromString,
                    response_serializer=a2a__pb2.Empty.SerializeToString,
            ),
            'SubscribeNetwork': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeNetwork,
                    request_deserializer=a2a__pb2.NetworkIDRequest.FromString,
                    response_serializer=a2a__pb2.BroadcastMessage.SerializeToString,
            ),
            'ClaimName': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimName,
                    request_deserializer=a2a__pb2.ClaimNameRequest.FromString,
                    response_serializer=a2a__pb2.NameClaimResponse.SerializeToString,
            ),
            'ResolveName': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveName,
                    request_deserializer=a2a__pb2.ResolveNameRequest.FromString,
                    response_serializer=a2a__pb2.NameClaimResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a.v1.A2ANode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a.v1.A2ANode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A2ANode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/GetIdentity',
            a2a__pb2.Empty.SerializeToString,
            a2a__pb2.AgentIdentity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishAgentCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/PublishAgentCard',
            a2a__pb2.AgentCard.SerializeToString,
            a2a__pb2.PublishResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/GetAgentCard',
            a2a__pb2.AgentIdentityRequest.SerializeToString,
            a2a__pb2.AgentCard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/FindAgents',
            a2a__pb2.CapabilityQuery.SerializeToString,
            a2a__pb2.AgentCard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/SendMessage',
            a2a__pb2.Message.SerializeToString,
            a2a__pb2.SendResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeInbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/SubscribeInbox',
            a2a__pb2.SubscribeRequest.SerializeToString,
            a2a__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/GetInbox',
            a2a__pb2.InboxQuery.SerializeToString,
            a2a__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOutbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/GetOutbox',
            a2a__pb2.OutboxQuery.SerializeToString,
            a2a__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/AckMessage',
            a2a__pb2.AckRequest.SerializeToString,
            a2a__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/CreateTask',
            a2a__pb2.CreateTaskRequest.SerializeToString,
            a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/GetTask',
            a2a__pb2.TaskID.SerializeToString,
            a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/UpdateTask',
            a2a__pb2.TaskStatusUpdate.SerializeToString,
            a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/CancelTask',
            a2a__pb2.TaskID.SerializeToString,
            a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishTaskEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/PublishTaskEvent',
            a2a__pb2.TaskEvent.SerializeToString,
            a2a__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/SubscribeTaskEvents',
            a2a__pb2.TaskID.SerializeToString,
            a2a__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/SendFile',
            a2a__pb2.SendFileRequest.SerializeToString,
            a2a__pb2.Artifact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/FetchFile',
            a2a__pb2.FetchFileRequest.SerializeToString,
            a2a__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/CreateThread',
            a2a__pb2.CreateThreadRequest.SerializeToString,
            a2a__pb2.Thread.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/GetThread',
            a2a__pb2.ThreadID.SerializeToString,
            a2a__pb2.Thread.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/AppendEntry',
            a2a__pb2.AppendEntryRequest.SerializeToString,
            a2a__pb2.AppendEntryResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThreadEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/GetThreadEntries',
            a2a__pb2.GetThreadEntriesRequest.SerializeToString,
            a2a__pb2.ThreadEntryWithPos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/SubscribeThread',
            a2a__pb2.SubscribeThreadRequest.SerializeToString,
            a2a__pb2.ThreadEntryWithPos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/Ping',
            a2a__pb2.PingRequest.SerializeToString,
            a2a__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/Health',
            a2a__pb2.Empty.SerializeToString,
            a2a__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/ListPeers',
            a2a__pb2.Empty.SerializeToString,
            a2a__pb2.PeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/Publish',
            a2a__pb2.PublishRequest.SerializeToString,
            a2a__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/SubscribeTopic',
            a2a__pb2.SubscribeTopicRequest.SerializeToString,
            a2a__pb2.TopicMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/SetWebhook',
            a2a__pb2.SetWebhookRequest.SerializeToString,
            a2a__pb2.WebhookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/ClearWebhook',
            a2a__pb2.Empty.SerializeToString,
            a2a__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/GetWebhook',
            a2a__pb2.Empty.SerializeToString,
            a2a__pb2.WebhookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/CreateNetwork',
            a2a__pb2.CreateNetworkRequest.SerializeToString,
            a2a__pb2.NetworkInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/JoinNetwork',
            a2a__pb2.JoinNetworkRequest.SerializeToString,
            a2a__pb2.NetworkInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/LeaveNetwork',
            a2a__pb2.NetworkIDRequest.SerializeToString,
            a2a__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/ListNetworks',
            a2a__pb2.Empty.SerializeToString,
            a2a__pb2.ListNetworksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NetworkMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/NetworkMembers',
            a2a__pb2.NetworkIDRequest.SerializeToString,
            a2a__pb2.NetworkMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/BroadcastNetwork',
            a2a__pb2.BroadcastRequest.SerializeToString,
            a2a__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2ANode/SubscribeNetwork',
            a2a__pb2.NetworkIDRequest.SerializeToString,
            a2a__pb2.BroadcastMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/ClaimName',
            a2a__pb2.ClaimNameRequest.SerializeToString,
            a2a__pb2.NameClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2ANode/ResolveName',
            a2a__pb2.ResolveNameRequest.SerializeToString,
            a2a__pb2.NameClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
